### ISSUE TITLE
Launching sensor processing sensor_launch error

### ISSUE THREAD

**Issue by SophiaSha** [appinho/ROS_Perception_Package_Kitti_Dataset#9]
Simon,

Where should I store the directory for `dataset_60` result from your GDrive? I know it needs to be renamed as `0060`. Everytime I try to do launch, it always gives me error 

`roslaunch: error: The following input files do not exist: 0060`

**Comment by appinho** [comment]
Hey @Sunflower369 ,

I updated the ReadMe to help you out with this problem. Let me know if this resolves your problem!

**Comment by appinho** [comment]
I updated the ReadMe. Now it should be working :)

**Comment by appinho** [comment]
Btw make sure to star the repo if you don’t mind :)

**Comment by SophiaSha** [comment]
Hello @appinho 

I've seen the updated README however I'm still getting an error. I did exactly the folder structure you posted on README. 

```
sps@sps:~/catkin_ws$ roslaunch sensor_processing sensor.launch 0060
Usage: roslaunch [options] [package] <filename> [arg_name:=value...]
       roslaunch [options] <filename> [<filename>...] [arg_name:=value...]

If <filename> is a single dash ('-'), launch XML is read from standard input.

roslaunch: error: The following input files do not exist: 0060
```

**Comment by appinho** [comment]
Ok check the following things please:

1) catkin_make builds the repo successfully?
2) source devel/setup.bash works fine?
3) If you only execute the rosbag play command and rviz you can see the data of the synchronized data bag file?

**Comment by SophiaSha** [comment]
1. yes
2. yes
3. I can run the rosbag and sync nicely. Only the `semantic_images` has an error. I think this is because the 0060 scenario result can't be loaded.

**Comment by appinho** [comment]
Ok thanks for your help! Usually, if you follow the directory it should work.

Are you sure that you executed the synchronization script just to make sure that the semantic images routine is executed.

You can test this by adding a ROS_INFO Code line in SensorFusion::processImage() and check if the code runs through it. Let me know if you think this method is executed or not :)

**Comment by SophiaSha** [comment]
It seems the semantic image not read properly. It could be where the `args` being defined. I know your launch file by default sets to `0060` scenario. Any idea on how to debug this? I might try to print out the sensorfusion for segmented images.

[ WARN] [1541399630.263789345]: Semantic image not read properly!
[ WARN] [1541399630.268995131]: Empty semantic point cloud!
[ INFO] [1541399630.269050175]: Publishing Sensor Fusion [110]: # PCL points [30948] # Ground [24285] # Elevated [6663] # Semantic [0] # Sparse Semantic [0]
[ INFO] [1541399630.370745239]: Ground plane estimation [111] # Points [10599] # Inliers [9848]  C [-0.007923][0.002726][0.999965][1.705010]
[ WARN] [1541399630.396164223]: Semantic image not read properly!
[ WARN] [1541399630.402088561]: Empty semantic point cloud!
[ INFO] [1541399630.402190316]: Publishing Sensor Fusion [111]: # PCL points [30959] # Ground [24105] # Elevated [6854] # Semantic [0] # Sparse Semantic [0]
[ INFO] [1541399630.446601872]: Ground plane estimation [112] # Points [10622] # Inliers [9875]  C [-0.008378][0.004300][0.999956][1.711730]
[ WARN] [1541399630.471228286]: Semantic image not read properly!
[ WARN] [1541399630.477490719]: Empty semantic point cloud!
[ INFO] [1541399630.477542451]: Publishing Sensor Fusion [112]: # PCL points [30966] # Ground [24165] # Elevated [6801] # Semantic [0] # Sparse Semantic [0]

**Comment by appinho** [comment]
Ok then try two things and let me know which ones work:

1) run the launch command without the 0060 at the end

2) remove the default="0060" from the sensor.launch and run the launch command with the 0060 at the end

Thank you for your help! If I would be close to a computer I run it myself but I’m on vacation ;)

**Comment by appinho** [comment]
@Sunflower369 any news? Does it work for you now?

**Comment by facade1801** [comment]
Maybe the command should be given like this:
roslaunch sensor_processing sensor.launch scenario:=0060
This works for me now.

**Comment by appinho** [comment]
Thank you @facade1801 for pointing this out! I’m adapting the ReadMe to clarify things more :)

Any other things you noticed that could be improved? Happy to hear from you
